/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function up(knex) {
  // PostgreSQL: the enum generated by knex.table.enum is actually a CHECK constraint.
  // We need to drop the existing constraint and recreate it with the new allowed value
  // 'interview-scheduled'. The constraint name is typically 'job_applications_status_check'.
  await knex.raw(`
    ALTER TABLE job_applications
    DROP CONSTRAINT IF EXISTS job_applications_status_check;

    ALTER TABLE job_applications
    ADD CONSTRAINT job_applications_status_check
      CHECK (status IN ('new','reviewing','interview-scheduled','shortlisted','rejected','hired'));
  `);
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function down(knex) {
  // Revert to the previous set without 'interview-scheduled'
  await knex.raw(`
    ALTER TABLE job_applications
    DROP CONSTRAINT IF EXISTS job_applications_status_check;

    ALTER TABLE job_applications
    ADD CONSTRAINT job_applications_status_check
      CHECK (status IN ('new','reviewing','shortlisted','rejected','hired'));
  `);
};


